Repository ut-issl/python-wings-interface, pull requests merged in 2022-03, with the labels that each got.

#13 Operation 作成API変更に伴う修正
  isslwings/operation.py
Labels: priority::high

#14 Update renovate settings
  .github/workflows/validate-renovate.yml
  renovate.json
Labels: priority::medium, tools

#15 pip install -e . でエラーが出る問題を解消
  setup.py
Labels: bug, priority::high, tools
